# Generated by Django 5.1.15 on 2026-08-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(db_index=True, max_length=16, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(max_length=64)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=16)),
                ('location', models.CharField(max_length=255)),
                ('lead_source', models.CharField(choices=[('Agent', 'Agent'), ('Referral', 'Referral'), ('Social Media', 'Social Media'), ('Web', 'Web')], max_length=32)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('fraud_risk_flag', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=16, null=True)),
                ('cross_sell_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['lead_source'], name='customers_c_lead_so_c65deb_idx'), models.Index(fields=['fraud_risk_flag'], name='customers_c_fraud_r_e6c300_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('age__gte', 18), ('age__lte', 120)), name='customer_age_valid'), models.CheckConstraint(condition=models.Q(('risk_score__isnull', True), models.Q(('risk_score__gte', 0), ('risk_score__lte', 1)), _connector='OR'), name='customer_risk_score_range'), models.CheckConstraint(condition=models.Q(('cross_sell_score__isnull', True), models.Q(('cross_sell_score__gte', 0), ('cross_sell_score__lte', 1)), _connector='OR'), name='customer_cross_sell_score_range')],
            },
        ),
    ]
