# Generated by Django 5.1.15 on 2026-08-14 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_status', models.CharField(choices=[('Approved', 'Approved'), ('Denied', 'Denied'), ('Filed', 'Filed')], db_index=True, max_length=16)),
                ('claim_amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='policies.policy')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['policy', 'claim_status'], name='claims_clai_policy__2a9679_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('claim_amount_usd__gte', 0)), name='claim_amount_non_negative'), models.CheckConstraint(condition=models.Q(('claim_status__in', ['Approved', 'Denied', 'Filed'])), name='claim_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='ClaimLoadAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_status', models.CharField(max_length=16)),
                ('source_amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('cleared', 'Cleared')], db_index=True, default='open', max_length=8)),
                ('cleared_reason', models.CharField(blank=True, choices=[('corrected', 'Corrected'), ('absent', 'Absent from latest load')], max_length=16, null=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('first_observed_at', models.DateTimeField()),
                ('last_observed_at', models.DateTimeField()),
                ('source_file', models.CharField(max_length=512)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_load_anomalies', to='policies.policy', unique=True)),
            ],
            options={
                'verbose_name_plural': 'claim load anomalies',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['status', 'cleared_reason'], name='claims_clai_status_cb8a29_idx')],
            },
        ),
    ]
