# Generated by Django 5.1.15 on 2026-08-10 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_type', models.CharField(choices=[('Life', 'Life'), ('Auto', 'Auto'), ('Property', 'Property'), ('Health', 'Health')], db_index=True, max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(db_index=True)),
                ('premium_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('renewal_probability', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='customers.customer')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['customer', 'policy_type'], name='policies_po_custome_49baff_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='policy_end_after_start'), models.CheckConstraint(condition=models.Q(('premium_usd__gt', 0)), name='policy_premium_positive'), models.CheckConstraint(condition=models.Q(('renewal_probability__isnull', True), models.Q(('renewal_probability__gte', 0), ('renewal_probability__lte', 1)), _connector='OR'), name='policy_renewal_probability_range'), models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('customer', 'policy_type'), name='policy_unique_live_type_per_customer')],
            },
        ),
    ]
