# Generated by Django 5.1.15 on 2026-08-01 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_identifier', models.CharField(max_length=254)),
                ('actor_role', models.CharField(blank=True, max_length=32)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('target_type', models.CharField(db_index=True, max_length=64)),
                ('target_id', models.CharField(db_index=True, max_length=64)),
                ('outcome', models.CharField(choices=[('succeeded', 'Succeeded'), ('refused', 'Refused')], max_length=16)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['target_type', 'target_id', 'timestamp'], name='audit_audit_target__46ccd6_idx')],
            },
        ),
    ]
