# Generated by Django 5.1.15 on 2026-08-19 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveSmallIntegerField()),
                ('tier', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('elevated', 'Elevated'), ('high', 'High')], db_index=True, max_length=16)),
                ('rule_set_version', models.CharField(db_index=True, max_length=16)),
                ('computed_at', models.DateTimeField()),
                ('computed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments_computed', to=settings.AUTH_USER_MODEL)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessment', to='customers.customer')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factor', models.CharField(choices=[('age', 'Customer age'), ('policy_type', 'Policy coverage type'), ('claims_history', 'Claims history'), ('claims_ratio', 'Claims-to-premium ratio'), ('denied_claim', 'Denied claim present')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('evaluated', 'Evaluated'), ('not_evaluable', 'Not evaluable')], max_length=16)),
                ('observed_value', models.CharField(blank=True, max_length=64)),
                ('band_label', models.CharField(max_length=64)),
                ('points', models.SmallIntegerField()),
                ('unevaluable_reason', models.CharField(blank=True, max_length=128)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='risk.riskassessment')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['tier', 'score'], name='risk_riskas_tier_b32847_idx'),
        ),
        migrations.AddConstraint(
            model_name='riskassessment',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='risk_score_range'),
        ),
        migrations.AddConstraint(
            model_name='riskassessment',
            constraint=models.CheckConstraint(condition=models.Q(('tier__in', ['low', 'moderate', 'elevated', 'high'])), name='risk_tier_valid'),
        ),
        migrations.AddIndex(
            model_name='riskfactor',
            index=models.Index(fields=['factor', 'points'], name='risk_riskfa_factor_e19f7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='riskfactor',
            constraint=models.UniqueConstraint(fields=('assessment', 'factor'), name='risk_factor_unique_per_assessment'),
        ),
        migrations.AddConstraint(
            model_name='riskfactor',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'not_evaluable'), models.Q(('unevaluable_reason', ''), _negated=True)), models.Q(('status', 'evaluated'), ('unevaluable_reason', '')), _connector='OR'), name='factor_reason_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='riskfactor',
            constraint=models.CheckConstraint(condition=models.Q(('points__gte', 0)), name='factor_points_non_negative'),
        ),
    ]
